name: Flutter

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: tag-version
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const fs = require('fs');

            const filePath = './pubspec.yaml';
            const fileContent = fs.readFileSync(filePath, 'utf-8');
            const regexPattern = /version: "([0-9\.]{6}([-\+][\w\.0-9]+)?)"/;

            const match = fileContent.match(regexPattern);
            const versionName = match ? match[1] : null;
            const prefixedVersionName = versionName ? `v${versionName}` : null;

            if (prefixedVersionName == null) {
              throw new Error('Version name not found in file: ' + filePath);
            }
            console.log('Version name: ' + prefixedVersionName);
            return prefixedVersionName;

      - name: Create tag
        run: |
          git tag ${{steps.tag-version.outputs.result}}
          git push --tags

  # build_android:
  #   name: Build Android Release
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Java
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: 'zulu'
  #         java-version: '11'

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #         flutter-version: '3.19.6'

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Build APK
  #       run: flutter build apk --release

  #     - name: Upload APK
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: app-release
  #         path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build iOS Release
    runs-on: macos-latest
    needs: [tag]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos build CODE_SIGNING_ALLOWED=NO

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/Release-iphoneos/Runner.app
