name: Flutter

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  # build_android:
  #   name: Build Android Release
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Java
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: 'zulu'
  #         java-version: '11'

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #         flutter-version: '3.19.6'

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Build APK
  #       run: flutter build apk --release

  #     - name: Upload APK
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: app-release
  #         path: build/app/outputs/flutter-apk/app-release.apk

  build_ios:
    name: Build iOS Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.6'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos build CODE_SIGNING_ALLOWED=NO

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-release
          path: build/ios/Release-iphoneos/Runner.app
